[package]
name = "chrono_plan"
version = "0.0.1"
edition = "2024_07"

[dependencies]
starknet = "2.15.1"
openzeppelin_access = "3.0.0"
openzeppelin_security = "3.0.0"
openzeppelin_interfaces = "2.1.0"
openzeppelin_macros = "3.0.0"
openzeppelin_token = "3.0.0"
openzeppelin_upgrades = "3.0.0"

[dev-dependencies]
snforge_std = "0.55.0"

[[target.starknet-contract]]
sierra = true
casm = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[tool.snforge.test]
build_external_contracts = [
    # "chrono_plan::application::schedule_proxy::ScheduleProxy",
]
